### ISSUE TITLE
Need initial content 

### ISSUE THREAD

**Issue by OR13** [w3c/did-rubric#2]
Suggest someone open a PR to add content to the index.html

**Comment by peacekeeper** [comment]
@jandrieu is this the latest version? https://docs.google.com/document/d/1rYdWiwawWmLOWtHRvT0GzYcdewW_OS9M2mAkENLFdtY/

Is this ready to be contributed to the WG and added into this repo?

**Comment by OR13** [comment]
Can we get an eta on the initial content?

**Comment by Identitywoman** [comment]
> @jandrieu is this the latest version? https://docs.google.com/document/d/1rYdWiwawWmLOWtHRvT0GzYcdewW_OS9M2mAkENLFdtY/
> 
> Is this ready to be contributed to the WG and added into this repo?

I was planning to write a pull request for the contents from the latest document into this repo. Both as a service to the community (also to increase my GitHub skills through doing).

**Comment by jandrieu** [comment]
Yes, that is the latest. @rhiaro has said she'd help turn that into ReSpec. Please reach out and inquire about the best way to help.

I expect the tables might be a bit of a chore to get right. Markdown isn't the best with tables.

**Comment by rhiaro** [comment]
@Identitywoman let me know if you're planning to do this so we don't both go ahead with it! Happy to step back and just be on call to help someone else, otherwise I'll probably get to this at the weekend
