### ISSUE TITLE
Prepare for TR

### ISSUE THREAD

**Issue by jandrieu** [w3c/did-rubric#26]
Create a static publication by downloading the respec rendering as HTML and placing it in a clearly addressable location within the repo, e.g., FPWD/2021-08-09 where the date is the anticipated publication date. Note that a Thursday publication date makes the most sense for Ivan, AND, the WG will need time to sign off on publication (which is likely a Tuesday call).

**Comment by iherman** [comment]
I think the date should be set on Aug 17 or 19:

1. Let us suppose the document is ready to go (ie, can be voted upon by the WG) on our meeting next week, ie, Tuesday, 10th
2. I would then ask the Director for an approval; these approvals are given on Friday, ie, Friday 13th.
3. In parallel, I would install the documents on the W3C site, and ask for a preliminary check by the Webmaster
3. (Manual) publications happen on Tuesdays or Thursdays, ie, the first available slot i on the 17th of August

A slight problem may be that I am not around on Monday the 16th if some last minute issue occurs (ie, somebody must be on stand-by to the webmaster if questions arise). That rarely happens for Notes, so I guess this is an acceptable risk. If we do not want to run the risk, we could move the publication to Thursday, the 19th. 

@brentzundel @burnburn

**Comment by brentzundel** [comment]
moving the publication date to the 19th makes sense to me

**Comment by jandrieu** [comment]
Done. We're in transition.
