### ISSUE TITLE
rename master branch

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-rubric#3]
# Summary
We should rename the branch `master` to `main` and use that going forward for our work.

From [Problematic Terminology in Open-Source](https://blog.carbonfive.com/2018/10/08/problematic-terminology-in-open-source/) on master/slave terminology in software:

> Use of this term is problematic. It references slavery to convey meaning about the relationship between two entities.

Removing this terminology from our workflow is a small gesture to include more people from marginalized groups in this project.

(I’m open to names other than `main`)

## Technical Steps

- [ ]  create main branch from master
- [ ]  make main the default GitHub branch
- [ ]  modify github/central to use main for release notes reloading
- [ ]  redirect PRs to main in w3c/did-rubric
- [ ]  move branch protections from master to main
- [ ]  modify docs to reference main instead of master
- [ ]  delete master branch to avoid confusion?

Feedback?

**Comment by selfissued** [comment]
Please no.  This wouldn't just affect the primary repository.  This would affect every branch, every fork, and every local clone, requiring manual steps by all participants to make parallel changes to these copies.  The chances of everyone getting this right are close to zero.

Using git correctly is already complicated enough.  Please don't make this repository even more complicated than usual.

**Comment by rhiaro** [comment]
I see only two forks, and one of them is brent. Given most (all?) of the work on this so far has been done in a google doc, I don't foresee too many people having cloned this repo (and fixing local clones as a simple matter of changing one word in the git config). I'm in favour of renaming asap, before it gets more complicated for this particular repo.

(PS. I'm using stable as the branch name for my personal projects, but no objection to main.)

**Comment by iherman** [comment]
@rhiaro, see my comments elsewhere: at the moment, the 'pages' feature of github does not work with any other branch name than 'master' or 'gh_pages'. (And, actually, I am not even 100% of the latter.) I think this means we must not change the branch name now, at least not until github takes care of that.

**Comment by brentzundel** [comment]
It looks like they're still working on tooling to make this easier: https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-
but these should be in place by the end of the year.

**Comment by iherman** [comment]
Done on 2021-03-25.
